[project]
authors = [
  {name = "Christopher Villamarín", email = "alexpila.314@gmail.com"},
]
dependencies = [
  "django>=5.2.2",
  "pillow>=11.2.1",
  "whitenoise>=6.9.0",
]
description = "Ad System for Django"
name = "adsystem"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"
