# Generated by Django 5.2.2 on 2025-06-08 21:29

import ads.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Anuncio')),
                ('image', models.ImageField(upload_to=ads.models.ad_image_upload_path, verbose_name='Imagen del Anuncio')),
                ('target_url', models.URLField(verbose_name='URL de Destino')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('total_clicks', models.PositiveIntegerField(default=0, verbose_name='Total de Clicks')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha/Hora del Click')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP del Usuario')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent del Navegador')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Sesión (hash)')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ads.ad', verbose_name='Anuncio')),
            ],
            options={
                'verbose_name': 'Click',
                'ordering': ['-timestamp'],
            },
        ),
    ]
