# Generated by Django 5.2.2 on 2025-06-26 22:59

import ads.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Campaña')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Fin')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Presupuesto')),
                ('target_audience', models.TextField(blank=True, verbose_name='Audiencia Objetivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Campaña',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Palabra Clave')),
            ],
            options={
                'verbose_name': 'Palabra Clave',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Anuncio')),
                ('image', models.ImageField(upload_to=ads.models.ad_image_upload_path, verbose_name='Imagen del Anuncio')),
                ('target_url', models.URLField(verbose_name='URL de Destino')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('total_clicks', models.PositiveIntegerField(default=0, verbose_name='Total de Clicks')),
                ('target_age_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad Mínima del Público')),
                ('target_age_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad Máxima del Público')),
                ('target_gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('A', 'Cualquiera')], default='A', max_length=1, verbose_name='Género del Público')),
                ('target_location', models.CharField(blank=True, help_text='Lista de ubicaciones separadas por comas (ej. España, México, Colombia)', max_length=255, verbose_name='Ubicación del Público')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.campaign', verbose_name='Campaña')),
                ('target_keywords', models.ManyToManyField(blank=True, help_text='Selecciona palabras clave que describan a tu audiencia.', to='ads.keyword', verbose_name='Palabras Clave del Público')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Carrusel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('ads', models.ManyToManyField(blank=True, related_name='carousels', to='ads.ad', verbose_name='Anuncios en el Carrusel')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousels', to='ads.campaign', verbose_name='Campaña')),
            ],
            options={
                'verbose_name': 'Carrusel de Anuncios',
                'verbose_name_plural': 'Carruseles de Anuncios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha/Hora del Click')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP del Usuario')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent del Navegador')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Sesión (hash)')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ads.ad', verbose_name='Anuncio')),
            ],
            options={
                'verbose_name': 'Click',
                'ordering': ['-timestamp'],
            },
        ),
    ]
