# Generated by Django 5.2.2 on 2025-06-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Carrusel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('ads', models.ManyToManyField(blank=True, related_name='carousels', to='ads.ad', verbose_name='Anuncios en el Carrusel')),
            ],
            options={
                'verbose_name': 'Carrusel de Anuncios',
                'verbose_name_plural': 'Carruseles de Anuncios',
                'ordering': ['name'],
            },
        ),
    ]
