# Generated by Django 5.2.2 on 2025-06-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='display_days_of_week',
            field=models.CharField(blank=True, help_text='Días de la semana separados por comas (ej. LUN,MAR,MIE)', max_length=60, verbose_name='Días de la Semana de Visualización'),
        ),
        migrations.AddField(
            model_name='ad',
            name='display_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Fin de Visualización'),
        ),
        migrations.AddField(
            model_name='ad',
            name='display_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio de Visualización'),
        ),
    ]
