# Generated by Django 5.2.2 on 2025-06-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Palabra Clave')),
            ],
            options={
                'verbose_name': 'Palabra Clave',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='target_age_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad Máxima del Público'),
        ),
        migrations.AddField(
            model_name='ad',
            name='target_age_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad Mínima del Público'),
        ),
        migrations.AddField(
            model_name='ad',
            name='target_gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('A', 'Cualquiera')], default='A', max_length=1, verbose_name='Género del Público'),
        ),
        migrations.AddField(
            model_name='ad',
            name='target_location',
            field=models.CharField(blank=True, help_text='Lista de ubicaciones separadas por comas (ej. España, México, Colombia)', max_length=255, verbose_name='Ubicación del Público'),
        ),
        migrations.AddField(
            model_name='ad',
            name='target_keywords',
            field=models.ManyToManyField(blank=True, help_text='Selecciona palabras clave que describan a tu audiencia.', to='ads.keyword', verbose_name='Palabras Clave del Público'),
        ),
    ]
