# Generated by Django 5.2.2 on 2025-06-26 23:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_total_impressions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha/Hora de Conversión')),
                ('conversion_type', models.CharField(max_length=100, verbose_name='Tipo de Conversión')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Conversión')),
                ('session_id', models.CharField(blank=True, help_text='ID de sesión del usuario que realizó la conversión, para atribución.', max_length=255, null=True, verbose_name='ID de Sesión (hash)')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='ads.ad', verbose_name='Anuncio')),
            ],
            options={
                'verbose_name': 'Conversión',
                'verbose_name_plural': 'Conversiones',
                'ordering': ['-timestamp'],
            },
        ),
    ]
